const AllData = [
    
    {
      id: 1,
      name: "Attack on Titan",
      short_image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKD-mfX3pgS2T5qt09QmIGo-LjiEdCJBGt8MthwmH_dcQ_Y_xt0TlGhicb3wahh-38gZ0&usqp=CAU",
      large_image:
        "https://www.safeshellvpn.com/o/pic/20240403/33c7010d-0ffc-4bce-bed2-8a4e958a7b78.png",
      imdb_rating: 9.0,
      watched: true,
      latest_released: "The Final Season - Part 2",
      trending: true,
      popular_tv_show: true,
      series: true,
      pg: "16+",
      cc: "Yes",
      time_length: "24m",
      story:
        "Humanity is on the brink of extinction as massive humanoid Titans terrorize the land. A young man named Eren Yeager vows to cleanse the Earth of these giant creatures after witnessing the destruction of his hometown.",
      released_date: "April 7, 2013",
      genres: ["Action", "Adventure", "Drama", "Fantasy", "Shounen"],
      studio: "Wit Studio",
      producer: "Production I.G",
      status: "Ongoing",
      episodes: 87,
      season_count: 4,
    },
    {
      id: 2,
      name: "Mob Psycho 100",
      short_image:
        "https://images-cdn.ubuy.co.in/63798e0b4d75021bac5d229a-laminated-mob-psycho-100-poster-anime.jpg",
      large_image:
        "https://miro.medium.com/v2/resize:fit:1200/0*zB9ZWoPPZ_cJpzf-.jpg",
      imdb_rating: 8.6,
      watched: true,
      latest_released: "Season 3",
      trending: true,
      popular_tv_show: true,
      series: true,
      pg: "13+",
      cc: "Yes",
      time_length: "24m",
      story:
        "A psychic middle schooler suppresses his powers to live a normal life but frequently finds himself using them to deal with supernatural threats.",
      released_date: "July 11, 2016",
      genres: ["Action", "Supernatural", "Comedy"],
      studio: "Bones",
      producer: "Warner Bros. Japan",
      status: "Ongoing",
      episodes: 37,
      season_count: 3,
    },
    {
      id: 3,
      name: "Erased",
      short_image:
        "https://m.media-amazon.com/images/M/MV5BZWQ2YmI5NWMtZTY2Mi00MGUxLWFhMmEtYjVjZjMwOTNkOThjXkEyXkFqcGc@._V1_.jpg",
      large_image:
        "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=1200,height=675/catalog/crunchyroll/09e46a3c3f53cb75e87af53393de7436.jpg",
      imdb_rating: 8.5,
      watched: true,
      latest_released: "Final Episode",
      trending: false,
      popular_tv_show: true,
      series: true,
      pg: "17+",
      cc: "Yes",
      time_length: "23m",
      story:
        "A man is sent back in time to prevent a series of kidnappings and murders.",
      released_date: "January 8, 2016",
      genres: ["Mystery", "Psychological", "Thriller", "Supernatural"],
      studio: "A-1 Pictures",
      producer: "Aniplex",
      status: "Completed",
      episodes: 12,
      season_count: 1,
    },
    {
      id: 4,
      name: "Toradora!",
      short_image:
        "https://m.media-amazon.com/images/M/MV5BMzBlZjI5N2EtZThiNy00NzhlLWE0NDgtODZlZmNhM2VmODllXkEyXkFqcGc@._V1_.jpg",
      large_image:
        "https://m.media-amazon.com/images/S/pv-target-images/7b4eb413c3b54a38b61ed1e28d16c9941997bee08f12845d0786b84a6c53f65b.jpg",
      imdb_rating: 8.0,
      watched: true,
      latest_released: "Final Episode",
      trending: false,
      popular_tv_show: true,
      series: true,
      pg: "13+",
      cc: "Yes",
      time_length: "23m",
      story:
        "A high school boy and girl form an unlikely friendship as they help each other with their crushes.",
      released_date: "October 2, 2008",
      genres: ["Comedy", "Romance", "Slice of Life"],
      studio: "J.C. Staff",
      producer: "Genco",
      status: "Completed",
      episodes: 25,
      season_count: 1,
    },
    {
      id: 5,
      name: "Death Note",
      short_image:
        "https://cdn.europosters.eu/image/750/death-note-from-the-shadows-i58005.jpg",
      large_image:
        "https://usercontent.one/wp/www.robjhayes.co.uk/wp-content/uploads/2016/12/deathnote.jpg",
      imdb_rating: 9.0,
      watched: true,
      latest_released: "Final Episode",
      trending: false,
      popular_tv_show: true,
      series: true,
      pg: "17+",
      cc: "Yes",
      time_length: "23m",
      story:
        "A high school student discovers a notebook that grants him the power to kill anyone whose name is written in it.",
      released_date: "October 4, 2006",
      genres: ["Thriller", "Psychological", "Supernatural"],
      studio: "Madhouse",
      producer: "VAP",
      status: "Completed",
      episodes: 37,
      season_count: 1,
    },
    {
      id: 6,
      name: "One Piece",
      short_image:
        "https://m.media-amazon.com/images/M/MV5BMTNjNGU4NTUtYmVjMy00YjRiLTkxMWUtNzZkMDNiYjZhNmViXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
      large_image:
        "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=1200,height=675/catalog/crunchyroll/a249096c7812deb8c3c2c907173f3774.jpg",
      imdb_rating: 8.9,
      watched: true,
      latest_released: "Wano Arc",
      trending: true,
      popular_tv_show: true,
      series: true,
      pg: "13+",
      cc: "Yes",
      time_length: "24m",
      story:
        "A group of pirates sets out on an epic adventure to find the legendary treasure known as One Piece.",
      released_date: "October 20, 1999",
      genres: ["Adventure", "Action", "Fantasy", "Shounen"],
      studio: "Toei Animation",
      producer: "Fuji TV",
      status: "Ongoing",
      episodes: 1120,
      season_count: 20,
    },
    {
      id: 7,
      name: "Jujutsu Kaisen",
      short_image:
        "https://mangajjk.com/wp-content/uploads/2024/05/Jujutsu-Kaisen-Wallpaper-Smartphone-1.webp",
      large_image:
        "https://gadgetmates.com/wp-content/uploads/2024/02/jujutsu-kaisen-jjk.webp",
      imdb_rating: 8.6,
      watched: true,
      latest_released: "Season 2",
      trending: true,
      popular_tv_show: true,
      series: true,
      pg: "16+",
      cc: "Yes",
      time_length: "23m",
      story:
        "A high school student becomes involved in a world of curses and sorcery after ingesting a powerful cursed object.",
      released_date: "October 3, 2020",
      genres: ["Action", "Supernatural", "Shounen"],
      studio: "MAPPA",
      producer: "Toho Animation",
      status: "Ongoing",
      episodes: 38,
      season_count: 2,
    },
    {
      id: 8,
      name: "Fullmetal Alchemist: Brotherhood",
      short_image:
        "https://m.media-amazon.com/images/M/MV5BNDczZWMyMjEtZDI0ZS00YThjLWE2MjEtNTIxNmVmZDhkNDg5XkEyXkFqcGc@._V1_.jpg",
      large_image:
        "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=1200,height=675/catalog/crunchyroll/ac0052958fa876ed2ef926920a88ec75.jpg",
      imdb_rating: 9.1,
      watched: true,
      latest_released: "Final Episode",
      trending: false,
      popular_tv_show: true,
      series: true,
      pg: "17+",
      cc: "Yes",
      time_length: "24m",
      story:
        "Two brothers use alchemy in their quest to restore their bodies after a failed alchemical experiment.",
      released_date: "April 5, 2009",
      genres: ["Action", "Adventure", "Drama", "Fantasy", "Shounen"],
      studio: "Bones",
      producer: "Aniplex",
      status: "Completed",
      episodes: 64,
      season_count: 1,
    },
    {
      id: 9,
      name: "Tokyo Revengers",
      short_image:
        "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=480,height=720/catalog/crunchyroll/70975a1227b453c1caf24fa05a93617d.jpg",
      large_image:
        "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=1200,height=675/catalog/crunchyroll/7923a0407dbdba324c56acec9f096c13.jpg",
      imdb_rating: 8.1,
      watched: false,
      latest_released: "Season 2",
      trending: true,
      popular_tv_show: true,
      series: true,
      pg: "16+",
      cc: "Yes",
      time_length: "23m",
      story:
        "A man travels back in time to prevent the death of his friends and alter his future.",
      released_date: "April 11, 2021",
      genres: ["Action", "Drama", "Supernatural", "Shounen"],
      studio: "Liden Films",
      producer: "Warner Bros. Japan",
      status: "Ongoing",
      episodes: 37,
      season_count: 2,
    },
    {
      id: 10,
      name: "Sword Art Online",
      short_image:
        "https://images.justwatch.com/poster/254572954/s718/sword-art-online-ii.jpg",
      large_image:
        "https://www.nintendo.com/eu/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_SwordArtOnlineHollowRealizationDeluxeEdition_image1600w.jpg",
      imdb_rating: 7.6,
      watched: true,
      latest_released: "War of Underworld",
      trending: false,
      popular_tv_show: true,
      series: true,
      pg: "13+",
      cc: "Yes",
      time_length: "24m",
      story:
        "Players are trapped in a virtual reality MMORPG where death in the game means death in real life.",
      released_date: "July 8, 2012",
      genres: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
      studio: "A-1 Pictures",
      producer: "Aniplex",
      status: "Completed",
      episodes: 96,
      season_count: 4,
    },
    {
      id: 11,
      name: "Bleach",
      short_image:
        "https://upload.wikimedia.org/wikipedia/en/7/72/Bleachanime.png",
      large_image:
        "https://static.fnac-static.com/multimedia/Images/FD/Comete/142862/CCP_IMG_1200x800/1879954.jpg",
      imdb_rating: 8.2,
      watched: true,
      latest_released: "Thousand-Year Blood War",
      trending: true,
      popular_tv_show: true,
      series: true,
      pg: "13+",
      cc: "Yes",
      time_length: "24m",
      story:
        "A teenager gains the powers of a Soul Reaper and protects the living world from dangerous spirits.",
      released_date: "October 5, 2004",
      genres: ["Action", "Adventure", "Supernatural", "Shounen"],
      studio: "Pierrot",
      producer: "TV Tokyo",
      status: "Ongoing",
      episodes: 366,
      season_count: 17,
    },
    {
      id: 12,
      name: "Spy x Family",
      short_image: "https://spyxmanga.com/wp-content/uploads/2021/12/sqd.png",
      large_image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS54bf8r4UfKwMBnLsyOAr-sDWDDslpcAkRRw&s",
      imdb_rating: 8.5,
      watched: true,
      latest_released: "Season 1 Part 2",
      trending: true,
      popular_tv_show: true,
      series: true,
      pg: "13+",
      cc: "Yes",
      time_length: "24m",
      story:
        "A spy must build a family to execute a mission, but his new family has secrets of their own.",
      released_date: "April 9, 2022",
      genres: ["Action", "Comedy", "Slice of Life", "Shounen"],
      studio: "Wit Studio, CloverWorks",
      producer: "Aniplex",
      status: "Ongoing",
      episodes: 25,
      season_count: 1,
    },
    {
      id: 13,
      name: "Dr. Stone",
      short_image:
        "https://i.redd.it/qn21xlgh4t341.jpg",
      large_image:
        "https://cdn.oneesports.gg/cdn-data/2024/08/Anime_DrStone_Character_SenkuuIshigami.jpg",
      imdb_rating: 8.2,
      watched: false,
      latest_released: "Season 3",
      trending: true,
      popular_tv_show: true,
      series: true,
      pg: "13+",
      cc: "Yes",
      time_length: "24m",
      story:
        "After a mysterious phenomenon turns humanity to stone, a scientific genius tries to rebuild civilization.",
      released_date: "July 5, 2019",
      genres: ["Adventure", "Sci-Fi", "Shounen"],
      studio: "TMS Entertainment",
      producer: "Toho Animation",
      status: "Ongoing",
      episodes: 46,
      season_count: 3,
    },
    {
      id: 14,
      name: "The Promised Neverland",
      short_image:
        "https://m.media-amazon.com/images/M/MV5BMGQ4ZGJhZTUtZDQ5Mi00NTI1LWEyYjItMzIxM2VlNmY4MDEyXkEyXkFqcGc@._V1_.jpg",
      large_image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRX8W7qMGpKsuqwJXVXoXCCD4fFQh0VbeOGHw&s",
      imdb_rating: 8.3,
      watched: true,
      latest_released: "Season 2",
      trending: false,
      popular_tv_show: true,
      series: true,
      pg: "13+",
      cc: "Yes",
      time_length: "24m",
      story:
        "A group of orphans uncovers a dark secret about their orphanage and plots their escape.",
      released_date: "January 11, 2019",
      genres: ["Mystery", "Psychological", "Thriller", "Shounen"],
      studio: "CloverWorks",
      producer: "Aniplex",
      status: "Completed",
      episodes: 23,
      season_count: 2,
    },
    {
      id: 15,
      name: "One Punch Man",
      short_image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQOzYITDzw8WTwQjygbtTEE1FxaSlrd7g2kA&s",
      large_image:
        "https://sm.ign.com/ign_in/screenshot/default/one-punch-man_kqxc.jpg",
      imdb_rating: 8.8,
      watched: true,
      latest_released: "Season 2",
      trending: true,
      popular_tv_show: true,
      series: true,
      pg: "17+",
      cc: "Yes",
      time_length: "24m",
      story:
        "A hero who can defeat any opponent with one punch seeks a worthy challenge.",
      released_date: "October 5, 2015",
      genres: ["Action", "Comedy", "Superhero", "Shounen"],
      studio: "Madhouse",
      producer: "Bandai Visual",
      status: "Ongoing",
      episodes: 24,
      season_count: 2,
    },
    {
      id: 16,
      name: "Hunter x Hunter",
      short_image:
        "https://m.media-amazon.com/images/M/MV5BYzYxOTlkYzctNGY2MC00MjNjLWIxOWMtY2QwYjcxZWIwMmEwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
      large_image:
        "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=1200,height=675/catalog/crunchyroll/2e54344c7cc1675af721b4021222230f.jpg",
      imdb_rating: 9.0,
      watched: true,
      latest_released: "Chimera Ant Arc",
      trending: true,
      popular_tv_show: true,
      series: true,
      pg: "13+",
      cc: "Yes",
      time_length: "24",
      story:
        "A young boy embarks on a journey to become a Hunter and find his father.",
      released_date: "October 2, 2011",
      genres: ["Action", "Adventure", "Fantasy", "Shounen"],
      studio: "Madhouse",
      producer: "Nippon TV",
      status: "Hiatus",
      episodes: 148,
      season_count: 6,
    },
    {
      id: 17,
      name: "Your Name",
      short_image:
        "https://m.media-amazon.com/images/M/MV5BMTIyNzFjNzItZmQ1MC00NzhjLThmMzYtZjRhN2Y3MmM2OGQyXkEyXkFqcGc@._V1_.jpg",
      large_image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJSdfZXAqF9S--ssdUEeUyCtNn5Z1m73c5zA&s",
      imdb_rating: 8.4,
      watched: true,
      latest_released: "Movie",
      trending: false,
      popular_tv_show: false,
      series: false,
      pg: "13+",
      cc: "Yes",
      time_length: "107m",
      story:
        "Two teenagers, one living in the countryside and the other in Tokyo, discover they are switching bodies and set out to meet each other.",
      released_date: "August 26, 2016",
      genres: ["Drama", "Fantasy", "Romance", "Supernatural"],
      studio: "CoMix Wave Films",
      producer: "Toho",
      status: "Completed",
      episodes: 1,
      season_count: 1,
    },
    {
      id: 18,
      name: "Steins;Gate",
      short_image:
        "https://m.media-amazon.com/images/M/MV5BZjI1YjZiMDUtZTI3MC00YTA5LWIzMmMtZmQ0NTZiYWM4NTYwXkEyXkFqcGc@._V1_.jpg",
      large_image:
        "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=1200,height=675/catalog/crunchyroll/ac6e22b27d285ed90e72744584d23434.jpe",
      imdb_rating: 8.8,
      watched: true,
      latest_released: "Steins;Gate 0",
      trending: false,
      popular_tv_show: true,
      series: true,
      pg: "17+",
      cc: "Yes",
      time_length: "24m",
      story:
        "A group of friends accidentally discovers a way to send messages to the past, which leads to unforeseen consequences.",
      released_date: "April 6, 2011",
      genres: ["Sci-Fi", "Thriller", "Drama"],
      studio: "White Fox",
      producer: "Kadokawa Shoten",
      status: "Completed",
      episodes: 24,
      season_count: 1,
    },
    {
      id: 19,
      name: "Neon Genesis Evangelion",
      short_image:
        "https://m.media-amazon.com/images/M/MV5BMGRiOWQyOTAtZDQ0Ny00NGRiLWIyYTYtZWM1MjNjNzg0ZjE3XkEyXkFqcGc@._V1_.jpg",
      large_image:
        "https://musicart.xboxlive.com/7/98d95c00-0000-0000-0000-000000000002/504/image.jpg",
      imdb_rating: 8.5,
      watched: true,
      latest_released: "End of Evangelion",
      trending: false,
      popular_tv_show: true,
      series: true,
      pg: "17+",
      cc: "Yes",
      time_length: "24m",
      story:
        "A teenager pilots a giant mecha to protect humanity from enigmatic beings known as Angels.",
      released_date: "October 4, 1995",
      genres: ["Action", "Psychological", "Mecha", "Sci-Fi"],
      studio: "Gainax",
      producer: "TV Tokyo",
      status: "Completed",
      episodes: 26,
      season_count: 1,
    },
    {
      id: 20,
      name: "My Hero Academia",
      short_image:
        "https://preview.redd.it/i-tried-to-make-the-textless-mha-season-7-key-visual-into-v0-c7tkfmvt1l7c1.jpg?width=640&crop=smart&auto=webp&s=20fa79d5b6b2ea9061f962268ac72305dccec031",
      large_image:
        "https://m.media-amazon.com/images/S/pv-target-images/fd59e3a3b34b8f8f837461572dc0453aeabde766fe43bb26fdab063cf6242ce2._SX1080_FMjpg_.jpg",
      imdb_rating: 8.4,
      watched: true,
      latest_released: "Season 6",
      trending: true,
      popular_tv_show: true,
      series: true,
      pg: "13+",
      cc: "Yes",
      time_length: "24m",
      story:
        "In a world where nearly everyone has superpowers, a boy without them dreams of becoming a hero.",
      released_date: "April 3, 2016",
      genres: ["Action", "Comedy", "Superhero", "Shounen"],
      studio: "Bones",
      producer: "Toho Animation",
      status: "Ongoing",
      episodes: 138,
      season_count: 6,
    },
    {
      id: 21,
      name: "Cowboy Bebop",
      short_image:
        "https://m.media-amazon.com/images/M/MV5BM2VhZjk2MWMtZjc2OC00YzA4LWI0NzAtZGQ1YjVkOTk5YzVlXkEyXkFqcGc@._V1_.jpg",
      large_image:
        "https://m.media-amazon.com/images/S/pv-target-images/3723b6933c62b03d206343c348d58f386610ba0ed774e27885cee3c1a0ae70c3.jpg",
      imdb_rating: 8.9,
      watched: true,
      latest_released: "Final Episode",
      trending: false,
      popular_tv_show: true,
      series: true,
      pg: "17+",
      cc: "Yes",
      time_length: "24m",
      story:
        "In the future, a group of bounty hunters known as 'Cowboys' travel across the galaxy on adventures.",
      released_date: "April 3, 1998",
      genres: ["Action", "Adventure", "Drama", "Sci-Fi"],
      studio: "Sunrise",
      producer: "Bandai Visual",
      status: "Completed",
      episodes: 26,
      season_count: 1,
    },
    {
      id: 22,
      name: "Vinland Saga",
      short_image:
        "https://upload.wikimedia.org/wikipedia/en/thumb/5/51/Vinland_Saga_volume_01_cover.jpg/220px-Vinland_Saga_volume_01_cover.jpg",
      large_image:
        "https://countzeroor.com/wp-content/uploads/2023/06/vinland-saga-season-2.webp",
      imdb_rating: 8.8,
      watched: true,
      latest_released: "Season 2",
      trending: true,
      popular_tv_show: true,
      series: true,
      pg: "17+",
      cc: "Yes",
      time_length: "24m",
      story:
        "A young Viking seeks revenge for the murder of his father while exploring the world of war and conquest.",
      released_date: "July 8, 2019",
      genres: ["Action", "Adventure", "Drama", "Historical"],
      studio: "Wit Studio",
      producer: "Kodansha",
      status: "Ongoing",
      episodes: 48,
      season_count: 2,
    },
    {
      id: 23,
      name: "Re:Zero - Starting Life in Another World",
      short_image:
        "https://m.media-amazon.com/images/M/MV5BNTY1M2NjMTItOGFhNi00NDU3LWExNzQtZGY2YWJlYzExNmU3XkEyXkFqcGc@._V1_.jpg",
      large_image:
        "https://m.media-amazon.com/images/S/pv-target-images/0559334408c12ef5e0a6a3d5d2df2e22e707c4c5fa8918889c898cf2c2573c11.jpg",
      imdb_rating: 8.1,
      watched: false,
      latest_released: "Season 2",
      trending: true,
      popular_tv_show: true,
      series: true,
      pg: "16+",
      cc: "Yes",
      time_length: "25m",
      story:
        "A young man is transported to another world and discovers he can rewind time by dying.",
      released_date: "April 4, 2016",
      genres: ["Fantasy", "Psychological", "Thriller", "Isekai"],
      studio: "White Fox",
      producer: "Kadokawa",
      status: "Ongoing",
      episodes: 50,
      season_count: 2,
    },
    {
      id: 24,
      name: "Haikyuu!!",
      short_image:
        "https://images-cdn.ubuy.co.in/6350c81143baae1ae1777ad6-haikyuu-poster-karasuno-high-school.jpg",
      large_image:
        "https://miro.medium.com/v2/resize:fit:2000/1*9fAwL_e64YXaEd8zPExMfw.jpeg",
      imdb_rating: 8.7,
      watched: true,
      latest_released: "Season 4",
      trending: true,
      popular_tv_show: true,
      series: true,
      pg: "13+",
      cc: "Yes",
      time_length: "24m",
      story:
        "A short high school student dreams of becoming a great volleyball player despite his stature.",
      released_date: "April 6, 2014",
      genres: ["Sports", "Comedy", "Drama", "Shounen"],
      studio: "Production I.G",
      producer: "Toho Animation",
      status: "Ongoing",
      episodes: 85,
      season_count: 4,
    },
    {
      id: 25,
      name: "Made in Abyss",
      short_image:
        "https://m.media-amazon.com/images/M/MV5BZjM4ODA5YTktNjliMC00NzI5LTk3ZTctZWYyYWEyNTJhMmQzXkEyXkFqcGc@._V1_.jpg",
      large_image:
        "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=1200,height=675/catalog/crunchyroll/532d3659db86ed0d86fcc57ef38acc45.jpe",
      imdb_rating: 8.4,
      watched: true,
      latest_released: "Season 2",
      trending: true,
      popular_tv_show: true,
      series: true,
      pg: "16+",
      cc: "Yes",
      time_length: "24m",
      story:
        "A girl and her robot friend venture into a mysterious abyss filled with ancient relics and strange creatures.",
      released_date: "July 7, 2017",
      genres: ["Adventure", "Fantasy", "Mystery", "Sci-Fi"],
      studio: "Kinema Citrus",
      producer: "Kadokawa",
      status: "Ongoing",
      episodes: 25,
      season_count: 2,
    },
    {
      id: 26,
      name: "Black Clover",
      short_image:
        "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=480,height=720/catalog/crunchyroll/e108ae17d8d0407417cac40eb52d849a.jpg",
      large_image:
        "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=1200,height=675/catalog/crunchyroll/0273e80242d80b0218f640e038269c18.jpg",
      imdb_rating: 8.0,
      watched: false,
      latest_released: "Final Episode",
      trending: true,
      popular_tv_show: true,
      series: true,
      pg: "13+",
      cc: "Yes",
      time_length: "23m",
      story:
        "A boy born without magic strives to become the Wizard King with the help of anti-magic.",
      released_date: "October 3, 2017",
      genres: ["Action", "Adventure", "Fantasy", "Shounen"],
      studio: "Pierrot",
      producer: "Avex Pictures",
      status: "Completed",
      episodes: 170,
      season_count: 4,
    },
    {
      id: 27,
      name: "No Game No Life",
      short_image:
        "https://m.media-amazon.com/images/M/MV5BOTk5ZDZhNGUtMDM2OS00Y2RkLWEwMmQtODg4ZTZiMGY1ZjFjXkEyXkFqcGc@._V1_.jpg",
      large_image:
        "https://m.media-amazon.com/images/S/pv-target-images/9472bf28f8f8b81df4271948663e7b8abea5594ae349ef27a958d680d95636b0.jpg",
      imdb_rating: 7.8,
      watched: true,
      latest_released: "Season 1",
      trending: false,
      popular_tv_show: true,
      series: true,
      pg: "16+",
      cc: "Yes",
      time_length: "23m",
      story:
        "Two siblings, expert gamers, are transported to a world where everything is decided by games.",
      released_date: "April 9, 2014",
      genres: ["Adventure", "Comedy", "Fantasy", "Isekai"],
      studio: "Madhouse",
      producer: "Kadokawa",
      status: "Completed",
      episodes: 12,
      season_count: 1,
    },
    {
      id: 28,
      name: "Assassination Classroom",
      short_image:
        "https://m.media-amazon.com/images/M/MV5BZjBkYmRiOTAtY2IwOS00ZWU3LTk3YjItNjMzYWZiMDE1MjcyXkEyXkFqcGc@._V1_.jpg",
      large_image:
        "https://rukminim2.flixcart.com/image/850/1000/jmqmpow0-1/poster/a/j/u/medium-athah-anime-assassination-classroom-irina-jelavi-tadaomi-original-imaf9kxmgcvnbgg4.jpeg?q=90&crop=false",
      imdb_rating: 8.0,
      watched: true,
      latest_released: "Season 2",
      trending: true,
      popular_tv_show: true,
      series: true,
      pg: "13+",
      cc: "Yes",
      time_length: "23m",
      story:
        "A group of students must kill their alien teacher before he destroys the Earth.",
      released_date: "January 9, 2015",
      genres: ["Action", "Comedy", "Shounen", "School"],
      studio: "Lerche",
      producer: "Aniplex",
      status: "Completed",
      episodes: 47,
      season_count: 2,
    },
    {
      id: 29,
      name: "Overlord",
      short_image:
        "https://m.media-amazon.com/images/M/MV5BYjNjNDBmZjAtMGZiMS00ODBkLWFjYWItZWQ1ZjEwOGNmZDBjXkEyXkFqcGc@._V1_.jpg",
      large_image: "https://i.ytimg.com/vi/uhlBqFj9kDw/maxresdefault.jpg",
      imdb_rating: 7.9,
      watched: true,
      latest_released: "Season 4",
      trending: true,
      popular_tv_show: true,
      series: true,
      pg: "17+",
      cc: "Yes",
      time_length: "24m",
      story:
        "A player trapped in a virtual reality game takes on the role of an evil overlord.",
      released_date: "July 7, 2015",
      genres: ["Action", "Fantasy", "Isekai", "Supernatural"],
      studio: "Madhouse",
      producer: "Kadokawa",
      status: "Ongoing",
      episodes: 52,
      season_count: 4,
    },
    {
      id: 30,
      name: "Demon Slayer: Kimetsu no Yaiba",
      short_image:
        "https://m.media-amazon.com/images/M/MV5BNmQ5Zjg2ZTYtMGZmNC00M2Y3LTgwZGQtYmQ3NWI5MDdhZWNjXkEyXkFqcGc@._V1_.jpg",
      large_image:
        "https://images.thedirect.com/media/article_full/demon-slayer-movie-2024-release-date.jpg",
      imdb_rating: 8.7,
      watched: true,
      latest_released: "Mugen Train Arc",
      trending: true,
      popular_tv_show: true,
      series: true,
      pg: "16+",
      cc: "Yes",
      time_length: "23m",
      story:
        "A young boy becomes a demon slayer after his family is slaughtered by demons.",
      released_date: "April 6, 2019",
      genres: ["Action", "Supernatural", "Shounen", "Historical"],
      studio: "Ufotable",
      producer: "Aniplex",
      status: "Ongoing",
      episodes: 44,
      season_count: 3,
    },
    {
      id: 31,
      name: "Akame ga Kill!",
      short_image:
        "https://m.media-amazon.com/images/M/MV5BYTQyZGQzMmUtNjcwMy00ZThiLWFmMzMtOTA0NTI3OWE0MTU0XkEyXkFqcGc@._V1_.jpg",
      large_image:
        "https://m.media-amazon.com/images/S/pv-target-images/955d09d7406ee6c28aa274d26bc7b7b12501cc63451eeac978e3e76f22070082.jpg",
      imdb_rating: 7.8,
      watched: true,
      latest_released: "Final Episode",
      trending: false,
      popular_tv_show: true,
      series: true,
      pg: "17+",
      cc: "Yes",
      time_length: "24m",
      story:
        "A young man joins an assassin group to overthrow a corrupt government.",
      released_date: "July 7, 2014",
      genres: ["Action", "Fantasy", "Drama", "Shounen"],
      studio: "White Fox",
      producer: "Toho Animation",
      status: "Completed",
      episodes: 24,
      season_count: 1,
    },
    {
      id: 32,
      name: "The Rising of the Shield Hero",
      short_image:
        "https://m.media-amazon.com/images/M/MV5BZjc4ZGZkNjMtZTRkYS00Mjk4LTgwMzAtMzg1MWZlZjcxNDRhXkEyXkFqcGc@._V1_.jpg",
      large_image: "https://images8.alphacoders.com/132/1320551.jpeg",
      imdb_rating: 8.0,
      watched: false,
      latest_released: "Season 2",
      trending: true,
      popular_tv_show: true,
      series: true,
      pg: "16+",
      cc: "Yes",
      time_length: "24m",
      story:
        "A man summoned to another world becomes the Shield Hero and must protect the kingdom from destruction.",
      released_date: "January 9, 2019",
      genres: ["Action", "Adventure", "Fantasy", "Isekai"],
      studio: "Kinema Citrus",
      producer: "Kadokawa",
      status: "Ongoing",
      episodes: 37,
      season_count: 2,
    },
    {
      id: 33,
      name: "Hellsing Ultimate",
      short_image:
        "https://m.media-amazon.com/images/M/MV5BZTA2OWJiYzgtZWFiOS00ZmYyLWFiMjMtYzg5YjNlMTA5NGJjXkEyXkFqcGc@._V1_.jpg",
      large_image:
        "https://animatedobservations.com/wp-content/uploads/2017/07/hellsing_seras_victoria_integra_fairbrook_hd-wallpaper-1817981.jpg?w=1200",
      imdb_rating: 8.3,
      watched: true,
      latest_released: "Final Episode",
      trending: false,
      popular_tv_show: true,
      series: true,
      pg: "17+",
      cc: "Yes",
      time_length: "50m",
      story:
        "The Hellsing Organization defends England from supernatural threats, led by the vampire Alucard.",
      released_date: "February 10, 2006",
      genres: ["Action", "Horror", "Supernatural"],
      studio: "Madhouse, Satelight",
      producer: "Geneon Universal Entertainment",
      status: "Completed",
      episodes: 10,
      season_count: 1,
    },
    {
      id: 34,
      name: "Code Geass: Lelouch of the Rebellion",
      short_image:
        "https://m.media-amazon.com/images/M/MV5BNjEyMzA0NDctNTQwMy00NDQ0LWExYjctOWYzMDcyYWYyMzFiXkEyXkFqcGc@._V1_.jpg",
      large_image:
        "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=1200,height=675/catalog/crunchyroll/073eaa35b1ce29bc29d57739b6479d02.jpg",
      imdb_rating: 8.7,
      watched: true,
      latest_released: "R2",
      trending: false,
      popular_tv_show: true,
      series: true,
      pg: "17+",
      cc: "Yes",
      time_length: "24m",
      story:
        "A prince with a powerful ability leads a rebellion against the tyrannical Britannian Empire.",
      released_date: "October 6, 2006",
      genres: ["Action", "Drama", "Mecha", "Supernatural"],
      studio: "Sunrise",
      producer: "Bandai Visual",
      status: "Completed",
      episodes: 50,
      season_count: 2,
    },
    {
      id: 35,
      name: "March Comes in Like a Lion",
      short_image:
        "https://m.media-amazon.com/images/M/MV5BMDJmZGZmNjQtMzE4NS00ZGRmLWFiMTQtM2EzZDhhZGNkY2FmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
      large_image:
        "https://preview.redd.it/e1efc0u4b3d61.jpg?width=1280&format=pjpg&auto=webp&s=0e8143ad94cc4a7941ca735e5a93799ba4c12761",
      imdb_rating: 8.5,
      watched: false,
      latest_released: "Season 2",
      trending: true,
      popular_tv_show: true,
      series: true,
      pg: "13+",
      cc: "Yes",
      time_length: "24m",
      story:
        "A young professional shogi player struggles with his life and relationships while learning to open up to others.",
      released_date: "October 8, 2016",
      genres: ["Drama", "Slice of Life", "Sports"],
      studio: "Shaft",
      producer: "Aniplex",
      status: "Completed",
      episodes: 44,
      season_count: 2,
    },
    {
      id: 36,
      name: "Your Lie in April",
      short_image:
        "https://m.media-amazon.com/images/M/MV5BZGMyYmFmNzgtMWQ4NS00MWE2LTg4YmEtZGY1MTBiODE0YmE5XkEyXkFqcGc@._V1_.jpg",
      large_image:
        "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=1200,height=675/catalog/crunchyroll/589632aedf2ed936e2c7ba95ed6ed5d4.jpe",
      imdb_rating: 8.6,
      watched: true,
      latest_released: "Final Episode",
      trending: false,
      popular_tv_show: true,
      series: true,
      pg: "13+",
      cc: "Yes",
      time_length: "22m",
      story:
        "A piano prodigy who lost his ability to play meets a free-spirited violinist who changes his life.",
      released_date: "October 10, 2014",
      genres: ["Drama", "Music", "Romance"],
      studio: "A-1 Pictures",
      producer: "Aniplex",
      status: "Completed",
      episodes: 22,
      season_count: 1,
    },
    {
      id: 37,
      name: "Kaguya-sama: Love is War",
      short_image:
        "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=480,height=720/catalog/crunchyroll/48b9c687382510e7ae195f61fee65c61.jpg",
      large_image:
        "https://m.media-amazon.com/images/S/pv-target-images/0363002a216398ef372ad4f6d5efad363dc8d378b5526d5d69f5917edf562eb9.jpg",
      imdb_rating: 8.5,
      watched: true,
      latest_released: "Season 3",
      trending: true,
      popular_tv_show: true,
      series: true,
      pg: "13+",
      cc: "Yes",
      time_length: "23m",
      story:
        "Two top-ranking student council members wage a battle of love, trying to get the other to confess first.",
      released_date: "January 12, 2019",
      genres: ["Comedy", "Romance", "Psychological", "School"],
      studio: "A-1 Pictures",
      producer: "Aniplex",
      status: "Ongoing",
      episodes: 37,
      season_count: 3,
    },
    {
      id: 38,
      name: "Attack on Titan: Junior High",
      short_image:
        "https://m.media-amazon.com/images/M/MV5BZmVkODZjODgtYjYzYS00YzMzLTliNmItMzAxMTAzNzkxMWI3XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
      large_image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSupIKDNPlO8RLzq4tyjrv6D-OPmmHw0OVXXg&s",
      imdb_rating: 7.2,
      watched: true,
      latest_released: "Final Episode",
      trending: false,
      popular_tv_show: true,
      series: true,
      pg: "13+",
      cc: "Yes",
      time_length: "17m",
      story:
        "The characters of Attack on Titan are re-imagined as students and teachers at a junior high school.",
      released_date: "October 4, 2015",
      genres: ["Comedy", "Parody", "School"],
      studio: "Production I.G",
      producer: "Kodansha",
      status: "Completed",
      episodes: 12,
      season_count: 1,
    },
    {
      id: 39,
      name: "The Quintessential Quintuplets",
      short_image:
        "https://m.media-amazon.com/images/M/MV5BODhmMGJjMjQtNDMzNi00ZTJmLWE4ZTItM2YwYjRlZWM5OWMxXkEyXkFqcGc@._V1_.jpg",
      large_image:
        "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=1200,height=675/catalog/crunchyroll/010634e9d1c76f0596248c1091e4586c.jpg",
      imdb_rating: 7.7,
      watched: false,
      latest_released: "Season 2",
      trending: true,
      popular_tv_show: true,
      series: true,
      pg: "13+",
      cc: "Yes",
      time_length: "23m",
      story:
        "A high school student becomes the private tutor for five identical sisters.",
      released_date: "January 10, 2019",
      genres: ["Comedy", "Romance", "Slice of Life"],
      studio: "Tezuka Productions",
      producer: "TBS",
      status: "Ongoing",
      episodes: 24,
      season_count: 2,
    },
    {
      id: 40,
      name: "Naruto",
      short_image:
        "https://images.justwatch.com/poster/138627711/s718/naruto.jpg",
      large_image:
        "https://www.lacasadeel.net/wp-content/uploads/2023/11/naruto-uzumaki1-jpg.webp",
      imdb_rating: 8.3,
      watched: true,
      latest_released: "Naruto Shippuden",
      trending: true,
      popular_tv_show: true,
      series: true,
      pg: "13+",
      cc: "Yes",
      time_length: "24m",
      story:
        "A young ninja strives to become the strongest and gain the title of Hokage.",
      released_date: "October 3, 2002",
      genres: ["Action", "Adventure", "Shounen", "Martial Arts"],
      studio: "Pierrot",
      producer: "TV Tokyo",
      status: "Completed",
      episodes: 720,
      season_count: 10,
    },
  ];
  
  export default AllData;
  